<a href="index.php?page=home_page" class="navlink">Home page</a>
<a href="index.php?page=site_layout" class="navlink">Site layout</a>
<a href="index.php?page=control_structures" class="navlink">Control structures</a>
<a href="index.php?page=string_functions" class="navlink">String functions</a>
<a href="index.php?page=web_forms" class="navlink">Web forms</a>
<a href="index.php?page=midterm_assessment" class="navlink">Midterm assessment</a>
<a href="index.php?page=state_information" class="navlink">State information</a>
<a href="index.php?page=user_templates" class="navlink">User templates</a>
<a href="index.php?page=final_project" class="navlink">Final project</a>